/* ida.c for the compiler comparison: the IDA* search of ../ida.c driven by
 * the test harness of assembly/ida.s, without the LED renderer.
 *
 * Runs the same three inputs as ida.s, prints each solution the same way,
 * checks T5 (the path really solves the state) and T6 (its length is the
 * known optimum), and exits with the number of failed checks (0 = all pass).
 *
 * RISC-V build for Ripes, then load the ELF:
 *   riscv64-unknown-elf-gcc -O2 -march=rv32i -mabi=ilp32 -nostdlib \
 *       compare/ida.c tables.c -lgcc -o compare/ida.elf
 *   Ripes --mode cli --src compare/ida.elf -t elf --proc RV32_ISS --iret
 * Host build, to check the output against ida.s:
 *   cc -O2 -std=c99 compare/ida.c tables.c -o compare/ida_host
 */
#include <stdint.h>
#ifndef __riscv
#include <stdio.h>
#endif

#define MAX_DEPTH 11
#define NUM_INPUTS 3
#define INPUT_LEN 15
#define NUM_MOVES 9
#define INVALID 255

// Defined in tables.c, generated by gen_tables --c
extern const uint8_t perm_heuristic[5040];
extern const uint8_t ori_heuristic[729];
extern const uint16_t perm_transition_flat[3 * 8192];
extern const uint16_t ori_transition_flat[3 * 1024];

// Same data as the .data section of ida.s
static const char inputs[NUM_INPUTS][INPUT_LEN] = {
    "12345671111111", // test 1: solved case
    "23745612123332", // test 2: 3 steps case
    "21345671111111", // test 3: 11 steps case
};
static const uint8_t expected[NUM_INPUTS] = {0, 3, 11}; // steps
static const uint8_t face_table[NUM_MOVES] = {0, 0, 0, 1, 1, 1, 2, 2, 2};
static const uint8_t turns_table[NUM_MOVES] = {1, 2, 3, 1, 2, 3, 1, 2, 3};
static const char face_char[3] = {'R', 'B', 'D'};
static const char invalid_msg[] = "invalid input\n";

typedef struct {
    uint16_t p_rank;
    uint16_t o_rank;
    uint8_t g;
    int8_t last_face;
    uint8_t move_index;
} StackNode;

// Global like path and stack in ida.s, instead of locals of solve_ida_star
static uint8_t path[MAX_DEPTH];
static StackNode stack[MAX_DEPTH + 1];

// ecall 11 in Ripes prints the character in a0, as ida.s does
static void print_char(char c)
{
#ifdef __riscv
    register int a0 __asm__("a0") = c;
    register int a7 __asm__("a7") = 11;
    __asm__ volatile("ecall" : : "r"(a0), "r"(a7) : "memory");
#else
    putchar(c);
#endif
}

// 0 if the input is a valid state, 1 otherwise
static int validate(const char *input)
{
    uint8_t seen = 0, sum = 0;
    if (input[14] != '\0')
        return 1;
    for (int i = 0; i < 7; i++) {
        // Unsigned subtraction folds the lower bound into the upper one
        uint8_t p = (uint8_t) (input[i] - '1');
        if (p >= 7)
            return 1;
        uint8_t mask = (uint8_t) (1U << p);
        if (seen & mask)
            return 1; // Duplicate cubie
        seen |= mask;
        uint8_t o = (uint8_t) (input[i + 7] - '1');
        if (o >= 3)
            return 1;
        sum += o;
    }
    while (sum >= 3) // sum % 3 without a remainder instruction
        sum -= 3;
    return sum != 0; // Twist parity
}

static uint16_t encode(const char *input, uint16_t *o_rank)
{
    uint16_t p_rank = 0, o = 0;
    for (int i = 0; i < 6; i++)
        o = (uint16_t) ((o << 1) + o + (input[i + 7] - '1')); // o * 3 + digit
    // i = 6 adds nothing: no cubie to its right, and the multiplier is 1
    for (int i = 0; i < 6; i++) {
        uint16_t smaller = 0;
        for (int j = i + 1; j < 7; j++)
            smaller += input[j] < input[i];
        uint16_t product = 0, x = p_rank;
        // product = p_rank * (7 - i) by shift and add
        for (uint8_t k = (uint8_t) (7 - i); k > 0; k >>= 1, x <<= 1)
            if (k & 1)
                product += x;
        p_rank = (uint16_t) (product + smaller);
    }
    *o_rank = o;
    return p_rank;
}

static uint8_t get_heuristic(uint16_t p_rank, uint16_t o_rank)
{
    uint8_t p_h = perm_heuristic[p_rank];
    uint8_t o_h = ori_heuristic[o_rank];
    return (p_h > o_h) ? p_h : o_h;
}

// Same search as ../ida.c: writes path and returns its length, or -1
static int solve_ida_star(uint16_t initial_p_rank, uint16_t initial_o_rank)
{
    uint8_t initial_h = get_heuristic(initial_p_rank, initial_o_rank);
    if (initial_h == 0)
        return 0;

    for (uint8_t bound = initial_h; bound <= MAX_DEPTH; bound++) {
        int8_t depth = 0;
        stack[0].p_rank = initial_p_rank;
        stack[0].o_rank = initial_o_rank;
        stack[0].g = 0;
        stack[0].last_face = -1;
        stack[0].move_index = 0;

        while (depth >= 0) {
            uint8_t h = get_heuristic(stack[depth].p_rank, stack[depth].o_rank);
            if (stack[depth].g + h > bound) { // Prune
                depth--;
                continue;
            }
            if (h == 0) { // Goal found
                for (int8_t k = 0; k < depth; k++)
                    path[k] = stack[k].move_index - 1;
                return depth;
            }
            if (stack[depth].move_index < NUM_MOVES) {
                uint8_t face = face_table[stack[depth].move_index];
                uint8_t turns = turns_table[stack[depth].move_index];
                if (face == stack[depth].last_face) {
                    stack[depth].move_index += 3;
                    continue;
                }
                stack[depth].move_index++;
                uint16_t next_p = stack[depth].p_rank;
                uint16_t next_o = stack[depth].o_rank;
                for (uint8_t i = 0; i < turns; i++) {
                    next_p = perm_transition_flat[(face << 13) + next_p];
                    next_o = ori_transition_flat[(face << 10) + next_o];
                }
                depth++;
                stack[depth].p_rank = next_p;
                stack[depth].o_rank = next_o;
                stack[depth].g = stack[depth - 1].g + 1;
                stack[depth].last_face = (int8_t) face;
                stack[depth].move_index = 0;
            } else {
                depth--; // All 9 moves tried
            }
        }
    }
    return -1;
}

// Prints path[0 .. length-1] as "R B' D2 ...", then '\n'
static void print_path(int length)
{
    for (int i = 0; i < length; i++) {
        if (i != 0)
            print_char(' ');
        uint8_t move = path[i];
        print_char(face_char[face_table[move]]);
        if (turns_table[move] == 2)
            print_char('2');
        else if (turns_table[move] == 3)
            print_char('\'');
    }
    print_char('\n');
}

// T5: 0 if replaying path from the start state reaches solved, 1 otherwise
static int verify_path(uint16_t p, uint16_t o, int length)
{
    for (int i = 0; i < length; i++) {
        uint8_t face = face_table[path[i]];
        for (uint8_t t = turns_table[path[i]]; t > 0; t--) {
            p = perm_transition_flat[(face << 13) + p];
            o = ori_transition_flat[(face << 10) + o];
        }
    }
    return (p | o) != 0;
}

int main(void)
{
    int failures = 0; // exit code, 0 = all checks pass
    for (int n = 0; n < NUM_INPUTS; n++) {
        const char *input = inputs[n];
        if (validate(input)) {
            for (const char *c = invalid_msg; *c; c++)
                print_char(*c);
            // Rejecting is correct only if expected says so
            failures += expected[n] != INVALID;
            continue;
        }
        uint16_t o_rank;
        uint16_t p_rank = encode(input, &o_rank);
        int length = solve_ida_star(p_rank, o_rank);
        print_path(length);
        failures += verify_path(p_rank, o_rank, length); // T5
        failures += length != expected[n];               // T6
    }
    return failures;
}

#ifdef __riscv
// No C runtime under -nostdlib: set gp for linker relaxation, call main, and
// exit through ecall 93 with its return value, as ida.s does. Ripes sets sp.
__asm__(".pushsection .text._start, \"ax\"\n"
        ".globl _start\n"
        "_start:\n"
        ".option push\n"
        ".option norelax\n"
        "    la   gp, __global_pointer$\n"
        ".option pop\n"
        "    call main\n"
        "    li   a7, 93\n"
        "    ecall\n"
        ".popsection\n");
#endif
